# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.io_external_secrets_v1beta1_cluster_external_secret_spec_external_secret_spec_target_template_config_map import IoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap  # noqa: E501
from kubernetes.client.rest import ApiException

class TestIoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap(unittest.TestCase):
    """IoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.io_external_secrets_v1beta1_cluster_external_secret_spec_external_secret_spec_target_template_config_map.IoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap()  # noqa: E501
        if include_optional :
            return IoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap(
                items = [
                    kubernetes.client.models.io_external_secrets_v1beta1_cluster_external_secret_spec_external_secret_spec_target_template_config_map_items.io_external_secrets_v1beta1_ClusterExternalSecret_spec_externalSecretSpec_target_template_configMap_items(
                        key = '0', 
                        template_as = '0', )
                    ], 
                name = '0'
            )
        else :
            return IoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap(
                items = [
                    kubernetes.client.models.io_external_secrets_v1beta1_cluster_external_secret_spec_external_secret_spec_target_template_config_map_items.io_external_secrets_v1beta1_ClusterExternalSecret_spec_externalSecretSpec_target_template_configMap_items(
                        key = '0', 
                        template_as = '0', )
                    ],
                name = '0',
        )

    def testIoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap(self):
        """Test IoExternalSecretsV1beta1ClusterExternalSecretSpecExternalSecretSpecTargetTemplateConfigMap"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
