# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.io_questdb_crd_v1alpha1_quest_db_node_spec_aws_security_group import IoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup  # noqa: E501
from kubernetes.client.rest import ApiException

class TestIoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup(unittest.TestCase):
    """IoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.io_questdb_crd_v1alpha1_quest_db_node_spec_aws_security_group.IoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup()  # noqa: E501
        if include_optional :
            return IoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup(
                allowed_cidrs = [
                    '0'
                    ], 
                ilp_node_port = 56, 
                psql_node_port = 56
            )
        else :
            return IoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup(
        )

    def testIoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup(self):
        """Test IoQuestdbCrdV1alpha1QuestDBNodeSpecAwsSecurityGroup"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
