# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.v1beta2_flow_schema_spec import V1beta2FlowSchemaSpec  # noqa: E501
from kubernetes.client.rest import ApiException

class TestV1beta2FlowSchemaSpec(unittest.TestCase):
    """V1beta2FlowSchemaSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test V1beta2FlowSchemaSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.v1beta2_flow_schema_spec.V1beta2FlowSchemaSpec()  # noqa: E501
        if include_optional :
            return V1beta2FlowSchemaSpec(
                distinguisher_method = kubernetes.client.models.v1beta2/flow_distinguisher_method.v1beta2.FlowDistinguisherMethod(
                    type = '0', ), 
                matching_precedence = 56, 
                priority_level_configuration = kubernetes.client.models.v1beta2/priority_level_configuration_reference.v1beta2.PriorityLevelConfigurationReference(
                    name = '0', ), 
                rules = [
                    kubernetes.client.models.v1beta2/policy_rules_with_subjects.v1beta2.PolicyRulesWithSubjects(
                        non_resource_rules = [
                            kubernetes.client.models.v1beta2/non_resource_policy_rule.v1beta2.NonResourcePolicyRule(
                                non_resource_ur_ls = [
                                    '0'
                                    ], 
                                verbs = [
                                    '0'
                                    ], )
                            ], 
                        resource_rules = [
                            kubernetes.client.models.v1beta2/resource_policy_rule.v1beta2.ResourcePolicyRule(
                                api_groups = [
                                    '0'
                                    ], 
                                cluster_scope = True, 
                                namespaces = [
                                    '0'
                                    ], 
                                resources = [
                                    '0'
                                    ], 
                                verbs = [
                                    '0'
                                    ], )
                            ], 
                        subjects = [
                            kubernetes.client.models.v1beta2/subject.v1beta2.Subject(
                                group = kubernetes.client.models.v1beta2/group_subject.v1beta2.GroupSubject(
                                    name = '0', ), 
                                kind = '0', 
                                service_account = kubernetes.client.models.v1beta2/service_account_subject.v1beta2.ServiceAccountSubject(
                                    name = '0', 
                                    namespace = '0', ), 
                                user = kubernetes.client.models.v1beta2/user_subject.v1beta2.UserSubject(
                                    name = '0', ), )
                            ], )
                    ]
            )
        else :
            return V1beta2FlowSchemaSpec(
                priority_level_configuration = kubernetes.client.models.v1beta2/priority_level_configuration_reference.v1beta2.PriorityLevelConfigurationReference(
                    name = '0', ),
        )

    def testV1beta2FlowSchemaSpec(self):
        """Test V1beta2FlowSchemaSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
