# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.io_tigera_operator_v1_installation_spec_calico_network_node_address_autodetection_v6 import IoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6  # noqa: E501
from kubernetes.client.rest import ApiException

class TestIoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6(unittest.TestCase):
    """IoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.io_tigera_operator_v1_installation_spec_calico_network_node_address_autodetection_v6.IoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6()  # noqa: E501
        if include_optional :
            return IoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6(
                can_reach = '0', 
                cidrs = [
                    '0'
                    ], 
                first_found = True, 
                interface = '0', 
                skip_interface = '0'
            )
        else :
            return IoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6(
        )

    def testIoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6(self):
        """Test IoTigeraOperatorV1InstallationSpecCalicoNetworkNodeAddressAutodetectionV6"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
