# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import kubernetes.client
from kubernetes.client.models.com_coreos_monitoring_v1_prometheus_spec_web_tls_config import ComCoreosMonitoringV1PrometheusSpecWebTlsConfig  # noqa: E501
from kubernetes.client.rest import ApiException

class TestComCoreosMonitoringV1PrometheusSpecWebTlsConfig(unittest.TestCase):
    """ComCoreosMonitoringV1PrometheusSpecWebTlsConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ComCoreosMonitoringV1PrometheusSpecWebTlsConfig
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = kubernetes.client.models.com_coreos_monitoring_v1_prometheus_spec_web_tls_config.ComCoreosMonitoringV1PrometheusSpecWebTlsConfig()  # noqa: E501
        if include_optional :
            return ComCoreosMonitoringV1PrometheusSpecWebTlsConfig(
                cert = kubernetes.client.models.com_coreos_monitoring_v1_prometheus_spec_web_tls_config_cert.com_coreos_monitoring_v1_Prometheus_spec_web_tlsConfig_cert(
                    config_map = kubernetes.client.models.com_coreos_monitoring_v1_pod_monitor_spec_oauth2_client_id_config_map.com_coreos_monitoring_v1_PodMonitor_spec_oauth2_clientId_configMap(
                        key = '0', 
                        name = '0', 
                        optional = True, ), 
                    secret = kubernetes.client.models.com_coreos_monitoring_v1_pod_monitor_spec_oauth2_client_id_secret.com_coreos_monitoring_v1_PodMonitor_spec_oauth2_clientId_secret(
                        key = '0', 
                        name = '0', 
                        optional = True, ), ), 
                cipher_suites = [
                    '0'
                    ], 
                kubernetes.client_auth_type = '0', 
                kubernetes.client_ca = kubernetes.client.models.com_coreos_monitoring_v1_prometheus_spec_web_tls_config_client_ca.com_coreos_monitoring_v1_Prometheus_spec_web_tlsConfig_client_ca(
                    config_map = kubernetes.client.models.com_coreos_monitoring_v1_pod_monitor_spec_oauth2_client_id_config_map.com_coreos_monitoring_v1_PodMonitor_spec_oauth2_clientId_configMap(
                        key = '0', 
                        name = '0', 
                        optional = True, ), 
                    secret = kubernetes.client.models.com_coreos_monitoring_v1_pod_monitor_spec_oauth2_client_id_secret.com_coreos_monitoring_v1_PodMonitor_spec_oauth2_clientId_secret(
                        key = '0', 
                        name = '0', 
                        optional = True, ), ), 
                curve_preferences = [
                    '0'
                    ], 
                key_secret = kubernetes.client.models.com_coreos_monitoring_v1_prometheus_spec_web_tls_config_key_secret.com_coreos_monitoring_v1_Prometheus_spec_web_tlsConfig_keySecret(
                    key = '0', 
                    name = '0', 
                    optional = True, ), 
                max_version = '0', 
                min_version = '0', 
                prefer_server_cipher_suites = True
            )
        else :
            return ComCoreosMonitoringV1PrometheusSpecWebTlsConfig(
                cert = kubernetes.client.models.com_coreos_monitoring_v1_prometheus_spec_web_tls_config_cert.com_coreos_monitoring_v1_Prometheus_spec_web_tlsConfig_cert(
                    config_map = kubernetes.client.models.com_coreos_monitoring_v1_pod_monitor_spec_oauth2_client_id_config_map.com_coreos_monitoring_v1_PodMonitor_spec_oauth2_clientId_configMap(
                        key = '0', 
                        name = '0', 
                        optional = True, ), 
                    secret = kubernetes.client.models.com_coreos_monitoring_v1_pod_monitor_spec_oauth2_client_id_secret.com_coreos_monitoring_v1_PodMonitor_spec_oauth2_clientId_secret(
                        key = '0', 
                        name = '0', 
                        optional = True, ), ),
                key_secret = kubernetes.client.models.com_coreos_monitoring_v1_prometheus_spec_web_tls_config_key_secret.com_coreos_monitoring_v1_Prometheus_spec_web_tlsConfig_keySecret(
                    key = '0', 
                    name = '0', 
                    optional = True, ),
        )

    def testComCoreosMonitoringV1PrometheusSpecWebTlsConfig(self):
        """Test ComCoreosMonitoringV1PrometheusSpecWebTlsConfig"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
