# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'description': 'str',
        'group_id': 'str',
        'group_name': 'str',
        'peering_status': 'str',
        'user_id': 'str',
        'vpc_id': 'str',
        'vpc_peering_connection_id': 'str'
    }

    attribute_map = {
        'description': 'description',
        'group_id': 'groupID',
        'group_name': 'groupName',
        'peering_status': 'peeringStatus',
        'user_id': 'userID',
        'vpc_id': 'vpcID',
        'vpc_peering_connection_id': 'vpcPeeringConnectionID'
    }

    def __init__(self, description=None, group_id=None, group_name=None, peering_status=None, user_id=None, vpc_id=None, vpc_peering_connection_id=None, local_vars_configuration=None):  # noqa: E501
        """AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._description = None
        self._group_id = None
        self._group_name = None
        self._peering_status = None
        self._user_id = None
        self._vpc_id = None
        self._vpc_peering_connection_id = None
        self.discriminator = None

        if description is not None:
            self.description = description
        if group_id is not None:
            self.group_id = group_id
        if group_name is not None:
            self.group_name = group_name
        if peering_status is not None:
            self.peering_status = peering_status
        if user_id is not None:
            self.user_id = user_id
        if vpc_id is not None:
            self.vpc_id = vpc_id
        if vpc_peering_connection_id is not None:
            self.vpc_peering_connection_id = vpc_peering_connection_id

    @property
    def description(self):
        """Gets the description of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501


        :return: The description of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.


        :param description: The description of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def group_id(self):
        """Gets the group_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501


        :return: The group_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.


        :param group_id: The group_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :type: str
        """

        self._group_id = group_id

    @property
    def group_name(self):
        """Gets the group_name of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501


        :return: The group_name of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :rtype: str
        """
        return self._group_name

    @group_name.setter
    def group_name(self, group_name):
        """Sets the group_name of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.


        :param group_name: The group_name of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :type: str
        """

        self._group_name = group_name

    @property
    def peering_status(self):
        """Gets the peering_status of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501


        :return: The peering_status of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :rtype: str
        """
        return self._peering_status

    @peering_status.setter
    def peering_status(self, peering_status):
        """Sets the peering_status of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.


        :param peering_status: The peering_status of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :type: str
        """

        self._peering_status = peering_status

    @property
    def user_id(self):
        """Gets the user_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501


        :return: The user_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.


        :param user_id: The user_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def vpc_id(self):
        """Gets the vpc_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501


        :return: The vpc_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :rtype: str
        """
        return self._vpc_id

    @vpc_id.setter
    def vpc_id(self, vpc_id):
        """Sets the vpc_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.


        :param vpc_id: The vpc_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :type: str
        """

        self._vpc_id = vpc_id

    @property
    def vpc_peering_connection_id(self):
        """Gets the vpc_peering_connection_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501


        :return: The vpc_peering_connection_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :rtype: str
        """
        return self._vpc_peering_connection_id

    @vpc_peering_connection_id.setter
    def vpc_peering_connection_id(self, vpc_peering_connection_id):
        """Sets the vpc_peering_connection_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.


        :param vpc_peering_connection_id: The vpc_peering_connection_id of this AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs.  # noqa: E501
        :type: str
        """

        self._vpc_peering_connection_id = vpc_peering_connection_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AwsK8sServicesEc2V1alpha1SecurityGroupSpecUserIDGroupPairs):
            return True

        return self.to_dict() != other.to_dict()
