# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'association_id': 'str',
        'cidr_block': 'str',
        'cidr_block_state': 'AwsK8sServicesEc2V1alpha1SubnetStatusIpv6CIDRBlockState'
    }

    attribute_map = {
        'association_id': 'associationID',
        'cidr_block': 'cidrBlock',
        'cidr_block_state': 'cidrBlockState'
    }

    def __init__(self, association_id=None, cidr_block=None, cidr_block_state=None, local_vars_configuration=None):  # noqa: E501
        """AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._association_id = None
        self._cidr_block = None
        self._cidr_block_state = None
        self.discriminator = None

        if association_id is not None:
            self.association_id = association_id
        if cidr_block is not None:
            self.cidr_block = cidr_block
        if cidr_block_state is not None:
            self.cidr_block_state = cidr_block_state

    @property
    def association_id(self):
        """Gets the association_id of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501


        :return: The association_id of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501
        :rtype: str
        """
        return self._association_id

    @association_id.setter
    def association_id(self, association_id):
        """Sets the association_id of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.


        :param association_id: The association_id of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501
        :type: str
        """

        self._association_id = association_id

    @property
    def cidr_block(self):
        """Gets the cidr_block of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501


        :return: The cidr_block of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501
        :rtype: str
        """
        return self._cidr_block

    @cidr_block.setter
    def cidr_block(self, cidr_block):
        """Sets the cidr_block of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.


        :param cidr_block: The cidr_block of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501
        :type: str
        """

        self._cidr_block = cidr_block

    @property
    def cidr_block_state(self):
        """Gets the cidr_block_state of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501


        :return: The cidr_block_state of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501
        :rtype: AwsK8sServicesEc2V1alpha1SubnetStatusIpv6CIDRBlockState
        """
        return self._cidr_block_state

    @cidr_block_state.setter
    def cidr_block_state(self, cidr_block_state):
        """Sets the cidr_block_state of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.


        :param cidr_block_state: The cidr_block_state of this AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet.  # noqa: E501
        :type: AwsK8sServicesEc2V1alpha1SubnetStatusIpv6CIDRBlockState
        """

        self._cidr_block_state = cidr_block_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AwsK8sServicesEc2V1alpha1VPCStatusCidrBlockAssociationSet):
            return True

        return self.to_dict() != other.to_dict()
