# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'end_time': 'str',
        'start_time': 'str'
    }

    attribute_map = {
        'end_time': 'endTime',
        'start_time': 'startTime'
    }

    def __init__(self, end_time=None, start_time=None, local_vars_configuration=None):  # noqa: E501
        """ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._end_time = None
        self._start_time = None
        self.discriminator = None

        if end_time is not None:
            self.end_time = end_time
        if start_time is not None:
            self.start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.  # noqa: E501

        EndTime is the end time in 24hr format.  # noqa: E501

        :return: The end_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.

        EndTime is the end time in 24hr format.  # noqa: E501

        :param end_time: The end_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                end_time is not None and not re.search(r'^((([01][0-9])|(2[0-3])):[0-5][0-9])$|(^24:00$)', end_time)):  # noqa: E501
            raise ValueError(r"Invalid value for `end_time`, must be a follow pattern or equal to `/^((([01][0-9])|(2[0-3])):[0-5][0-9])$|(^24:00$)/`")  # noqa: E501

        self._end_time = end_time

    @property
    def start_time(self):
        """Gets the start_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.  # noqa: E501

        StartTime is the start time in 24hr format.  # noqa: E501

        :return: The start_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.

        StartTime is the start time in 24hr format.  # noqa: E501

        :param start_time: The start_time of this ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes.  # noqa: E501
        :type: str
        """
        if (self.local_vars_configuration.client_side_validation and
                start_time is not None and not re.search(r'^((([01][0-9])|(2[0-3])):[0-5][0-9])$|(^24:00$)', start_time)):  # noqa: E501
            raise ValueError(r"Invalid value for `start_time`, must be a follow pattern or equal to `/^((([01][0-9])|(2[0-3])):[0-5][0-9])$|(^24:00$)/`")  # noqa: E501

        self._start_time = start_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ComCoreosMonitoringV1alpha1AlertmanagerConfigSpecTimes):
            return True

        return self.to_dict() != other.to_dict()
