# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class IoArgoprojV1alpha1AppProjectSpecOrphanedResources(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'ignore': 'list[IoArgoprojV1alpha1AppProjectSpecOrphanedResourcesIgnore]',
        'warn': 'bool'
    }

    attribute_map = {
        'ignore': 'ignore',
        'warn': 'warn'
    }

    def __init__(self, ignore=None, warn=None, local_vars_configuration=None):  # noqa: E501
        """IoArgoprojV1alpha1AppProjectSpecOrphanedResources - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._ignore = None
        self._warn = None
        self.discriminator = None

        if ignore is not None:
            self.ignore = ignore
        if warn is not None:
            self.warn = warn

    @property
    def ignore(self):
        """Gets the ignore of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.  # noqa: E501

        Ignore contains a list of resources that are to be excluded from orphaned resources monitoring  # noqa: E501

        :return: The ignore of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.  # noqa: E501
        :rtype: list[IoArgoprojV1alpha1AppProjectSpecOrphanedResourcesIgnore]
        """
        return self._ignore

    @ignore.setter
    def ignore(self, ignore):
        """Sets the ignore of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.

        Ignore contains a list of resources that are to be excluded from orphaned resources monitoring  # noqa: E501

        :param ignore: The ignore of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.  # noqa: E501
        :type: list[IoArgoprojV1alpha1AppProjectSpecOrphanedResourcesIgnore]
        """

        self._ignore = ignore

    @property
    def warn(self):
        """Gets the warn of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.  # noqa: E501

        Warn indicates if warning condition should be created for apps which have orphaned resources  # noqa: E501

        :return: The warn of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.  # noqa: E501
        :rtype: bool
        """
        return self._warn

    @warn.setter
    def warn(self, warn):
        """Sets the warn of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.

        Warn indicates if warning condition should be created for apps which have orphaned resources  # noqa: E501

        :param warn: The warn of this IoArgoprojV1alpha1AppProjectSpecOrphanedResources.  # noqa: E501
        :type: bool
        """

        self._warn = warn

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoArgoprojV1alpha1AppProjectSpecOrphanedResources):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoArgoprojV1alpha1AppProjectSpecOrphanedResources):
            return True

        return self.to_dict() != other.to_dict()
