# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.25.12
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'max_retries': 'int',
        'retry_interval': 'str'
    }

    attribute_map = {
        'max_retries': 'maxRetries',
        'retry_interval': 'retryInterval'
    }

    def __init__(self, max_retries=None, retry_interval=None, local_vars_configuration=None):  # noqa: E501
        """IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._max_retries = None
        self._retry_interval = None
        self.discriminator = None

        if max_retries is not None:
            self.max_retries = max_retries
        if retry_interval is not None:
            self.retry_interval = retry_interval

    @property
    def max_retries(self):
        """Gets the max_retries of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.  # noqa: E501


        :return: The max_retries of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.  # noqa: E501
        :rtype: int
        """
        return self._max_retries

    @max_retries.setter
    def max_retries(self, max_retries):
        """Sets the max_retries of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.


        :param max_retries: The max_retries of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.  # noqa: E501
        :type: int
        """

        self._max_retries = max_retries

    @property
    def retry_interval(self):
        """Gets the retry_interval of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.  # noqa: E501


        :return: The retry_interval of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.  # noqa: E501
        :rtype: str
        """
        return self._retry_interval

    @retry_interval.setter
    def retry_interval(self, retry_interval):
        """Sets the retry_interval of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.


        :param retry_interval: The retry_interval of this IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings.  # noqa: E501
        :type: str
        """

        self._retry_interval = retry_interval

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoExternalSecretsV1alpha1ClusterSecretStoreSpecRetrySettings):
            return True

        return self.to_dict() != other.to_dict()
