# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.20.7
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'advertise_address': 'str',
        'bind_port': 'int'
    }

    attribute_map = {
        'advertise_address': 'advertiseAddress',
        'bind_port': 'bindPort'
    }

    def __init__(self, advertise_address=None, bind_port=None, local_vars_configuration=None):  # noqa: E501
        """IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._advertise_address = None
        self._bind_port = None
        self.discriminator = None

        self.advertise_address = advertise_address
        self.bind_port = bind_port

    @property
    def advertise_address(self):
        """Gets the advertise_address of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.  # noqa: E501

        AdvertiseAddress sets the IP address for the API server to advertise.  # noqa: E501

        :return: The advertise_address of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.  # noqa: E501
        :rtype: str
        """
        return self._advertise_address

    @advertise_address.setter
    def advertise_address(self, advertise_address):
        """Sets the advertise_address of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.

        AdvertiseAddress sets the IP address for the API server to advertise.  # noqa: E501

        :param advertise_address: The advertise_address of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and advertise_address is None:  # noqa: E501
            raise ValueError("Invalid value for `advertise_address`, must not be `None`")  # noqa: E501

        self._advertise_address = advertise_address

    @property
    def bind_port(self):
        """Gets the bind_port of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.  # noqa: E501

        BindPort sets the secure port for the API Server to bind to. Defaults to 6443.  # noqa: E501

        :return: The bind_port of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.  # noqa: E501
        :rtype: int
        """
        return self._bind_port

    @bind_port.setter
    def bind_port(self, bind_port):
        """Sets the bind_port of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.

        BindPort sets the secure port for the API Server to bind to. Defaults to 6443.  # noqa: E501

        :param bind_port: The bind_port of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and bind_port is None:  # noqa: E501
            raise ValueError("Invalid value for `bind_port`, must not be `None`")  # noqa: E501

        self._bind_port = bind_port

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationControlPlaneLocalAPIEndpoint):
            return True

        return self.to_dict() != other.to_dict()
