# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.20.7
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'kube_config_path': 'str'
    }

    attribute_map = {
        'kube_config_path': 'kubeConfigPath'
    }

    def __init__(self, kube_config_path=None, local_vars_configuration=None):  # noqa: E501
        """IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._kube_config_path = None
        self.discriminator = None

        self.kube_config_path = kube_config_path

    @property
    def kube_config_path(self):
        """Gets the kube_config_path of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile.  # noqa: E501

        KubeConfigPath is used to specify the actual file path or URL to the kubeconfig file from which to load cluster information  # noqa: E501

        :return: The kube_config_path of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile.  # noqa: E501
        :rtype: str
        """
        return self._kube_config_path

    @kube_config_path.setter
    def kube_config_path(self, kube_config_path):
        """Sets the kube_config_path of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile.

        KubeConfigPath is used to specify the actual file path or URL to the kubeconfig file from which to load cluster information  # noqa: E501

        :param kube_config_path: The kube_config_path of this IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and kube_config_path is None:  # noqa: E501
            raise ValueError("Invalid value for `kube_config_path`, must not be `None`")  # noqa: E501

        self._kube_config_path = kube_config_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoXK8sClusterBootstrapV1alpha3KubeadmConfigSpecJoinConfigurationDiscoveryFile):
            return True

        return self.to_dict() != other.to_dict()
