# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.20.7
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kubernetes.client.configuration import Configuration


class IoXK8sHncV1alpha2HierarchyConfigurationSpec(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'allow_cascading_deletion': 'bool',
        'parent': 'str'
    }

    attribute_map = {
        'allow_cascading_deletion': 'allowCascadingDeletion',
        'parent': 'parent'
    }

    def __init__(self, allow_cascading_deletion=None, parent=None, local_vars_configuration=None):  # noqa: E501
        """IoXK8sHncV1alpha2HierarchyConfigurationSpec - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._allow_cascading_deletion = None
        self._parent = None
        self.discriminator = None

        if allow_cascading_deletion is not None:
            self.allow_cascading_deletion = allow_cascading_deletion
        if parent is not None:
            self.parent = parent

    @property
    def allow_cascading_deletion(self):
        """Gets the allow_cascading_deletion of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.  # noqa: E501

        AllowCascadingDeletion indicates if the subnamespaces of this namespace are allowed to cascading delete.  # noqa: E501

        :return: The allow_cascading_deletion of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.  # noqa: E501
        :rtype: bool
        """
        return self._allow_cascading_deletion

    @allow_cascading_deletion.setter
    def allow_cascading_deletion(self, allow_cascading_deletion):
        """Sets the allow_cascading_deletion of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.

        AllowCascadingDeletion indicates if the subnamespaces of this namespace are allowed to cascading delete.  # noqa: E501

        :param allow_cascading_deletion: The allow_cascading_deletion of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.  # noqa: E501
        :type: bool
        """

        self._allow_cascading_deletion = allow_cascading_deletion

    @property
    def parent(self):
        """Gets the parent of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.  # noqa: E501

        Parent indicates the parent of this namespace, if any.  # noqa: E501

        :return: The parent of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.  # noqa: E501
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.

        Parent indicates the parent of this namespace, if any.  # noqa: E501

        :param parent: The parent of this IoXK8sHncV1alpha2HierarchyConfigurationSpec.  # noqa: E501
        :type: str
        """

        self._parent = parent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IoXK8sHncV1alpha2HierarchyConfigurationSpec):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, IoXK8sHncV1alpha2HierarchyConfigurationSpec):
            return True

        return self.to_dict() != other.to_dict()
